---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: chatbot-0718-vllm
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: chatbot-0718-vllm 
  name: chatbot-0718-vllm
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi